# @Time   : 2020/9/18
# @Author : Shanlei Mu
# @Email  : slmu@ruc.edu.cn


dataset2class = {
    'ml-100k': 'ML100KDataset',
    'ml-1m': 'ML1MDataset',
    'ml-10m': 'ML10MDataset',
    'ml-20m': 'ML20MDataset',
    'avazu': 'AVAZUDataset',
    'adult': 'ADULTDataset',
    'tmall': 'TMALLDataset',
    'netflix': 'NETFLIXDataset',
    'criteo': 'CRITEODataset',
    'foursquare': 'FOURSQUAREDataset',
    'diginetica': 'DIGINETICADataset',
    'anime': 'ANIMEDataset',
    'epinions': 'EPINIONSDataset',
    'gowalla': 'GOWALLADataset',
    'lfm1b': 'LFM1bDataset',
    'book-crossing': 'BOOKCROSSINGDataset',
    'ipinyou': 'IPINYOUDataset',
    'steam': 'STEAMDataset',
    'phishing-website': 'PHISHINGWEBDataset',
    'pinterest': 'PINTERESTDataset',
    'jester': 'JESTERDataset',
    'douban': 'DOUBANDataset',
    'kdd2010-algebra2006': 'KDD2010Algebra2006Dataset',
    'kdd2010-algebra2008': 'KDD2010Algebra2008Dataset',
    'kdd2010-bridge-to-algebra2006': 'KDD2010BridgeToAlgebra2006Dataset',
    'amazon_apps_for_android': 'AmazonAppsForAndroidDataset',
    'amazon_beauty': 'AmazonBeautyDataset',
    'amazon_tools_and_home_improvement': 'AmazonToolsAndHomeImprovementDataset',
    'amazon_books': 'AmazonBooksDataset',
    'amazon_instant_video': 'AmazonInstantVideoDataset',
    'amazon_digital_music': 'AmazonDigitalMusicDataset',
    'amazon_movies_and_tv': 'AmazonMoviesAndTVDataset',
    'amazon_automotive': 'AmazonAutomotiveDataset',
    'amazon_baby': 'AmazonBabyDataset',
    'amazon_clothing_shoes_and_jewelry': 'AmazonClothingShoesAndJewelryDataset',
    'amazon_cell_phones_and_accessories': 'AmazonCellPhonesAndAccessoriesDataset',
    'amazon_patio_lawn_and_garden': 'AmazonPatioLawnAndGardenDataset',
    'amazon_kindle_store': 'AmazonKindleStoreDataset',
    'amazon_home_and_kitchen': 'AmazonHomeAndKitchenDataset',
    'amazon_grocery_and_gourmet_food': 'AmazonGroceryAndGourmetFoodDataset',
    'amazon_health_and_personal_care': 'AmazonHealthAndPersonalCareDataset',
    'amazon_pet_supplies': 'AmazonPetSuppliesDataset',
    'amazon_sports_and_outdoors': 'AmazonSportsAndOutdoorsDataset',
    'amazon_toys_and_games': 'AmazonToysAndGamesDataset',
    'amazon_electronics': 'AmazonElectronicsDataset',
    'amazon_office_products': 'AmazonOfficeProductsDataset',
    'amazon_video_games': 'AmazonVideoGamesDataset',
    'amazon_musical_instruments': 'AmazonMusicalInstrumentsDataset',
    'yelp': 'YELPDataset',
    'lastfm': 'LASTFMDataset',
    'yoochoose': 'YOOCHOOSEDataset',
    'yahoo-music': 'YAHOOMUSICDataset',
    'ta-feng': 'TAFENGDataset',
    'retailrocket': 'RETAILROCKETDataset',
    'mind_large_train': 'MINDLargeTrainDataset',
    'mind_large_dev': 'MINDLargeDevDataset',
    'mind_small_train': 'MINDSmallTrainDataset',
    'mind_small_dev': 'MINDSmallDevDataset',
    'cosmetics': 'CosmeticsDataset'
}

click_dataset = {
    'YOOCHOOSEDataset',
    'RETAILROCKETDataset',
    'TMALLDataset',
    'IPINYOUDataset',
    'TAFENGDataset',
    'LFM1bDataset',
    'GOWALLADataset',
    'DIGINETICADataset',
    'FOURSQUAREDataset',
    'STEAMDataset'
}

multiple_dataset = {
    'YOOCHOOSEDataset',
    'RETAILROCKETDataset',
    'TAFENGDataset',
    'TMALLDataset',
    'IPINYOUDataset',
    'LFM1bDataset'
}